import { type NextRequest, NextResponse } from "next/server"
import { supabase } from "@/lib/supabaseClient"

// Make sure this route is always dynamic (not prerendered at build time)
export const dynamic = "force-dynamic"

// GET /api/issues
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const citizenId = searchParams.get("citizenId")
  const status = searchParams.get("status")
  const category = searchParams.get("category")

  // Start Supabase query
  // 👇 Make sure your table name is exactly "issues"
  let query = supabase
    .from("issues")
    .select("*")
    .order("created_at", { ascending: false })

  // Apply filters if provided
  if (citizenId) {
    // Adjust column name if needed (e.g., "citizen_id")
    query = query.eq("citizen_id", citizenId)
  }

  if (status) {
    query = query.eq("status", status)
  }

  if (category) {
    query = query.eq("category", category)
  }

  const { data, error } = await query

  if (error) {
    console.error("Error fetching issues:", error)
    return NextResponse.json(
      { error: "Failed to fetch issues" },
      { status: 500 },
    )
  }

  // Supabase returns plain JS objects → JSON serializable ✅
  return NextResponse.json(data ?? [])
}

// POST /api/issues
export async function POST(request: NextRequest) {
  try {
    const issueData = await request.json()

    // Map incoming body to your DB columns
    // Adjust these fields to match your "issues" table schema
    const payload = {
      // id will be generated by Supabase if "id" has a default
      title: issueData.title,
      description: issueData.description,
      citizen_id: issueData.citizenId ?? null,
      category: issueData.category ?? null,
      department_id: issueData.departmentId ?? null,
      status: "pending", // default like your mock
      // created_at / updated_at can be defaults in DB
    }

    const { data, error } = await supabase
      .from("issues")
      .insert([payload])
      .select("*")
      .single()

    if (error) {
      console.error("Error creating issue:", error)
      return NextResponse.json(
        { error: "Failed to create issue" },
        { status: 500 },
      )
    }

    return NextResponse.json(data, { status: 201 })
  } catch (error) {
    console.error("Error in POST /api/issues:", error)
    return NextResponse.json(
      { error: "Failed to create issue" },
      { status: 500 },
    )
  }
}
